server:
  port: 8080

logger:
  level: "dev"

database:
  dsn: root:root@tcp(127.0.0.1:3306)/aicityapplication?charset=utf8mb4&parseTime=True&loc=Local

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

# rabbitmq:
#   url: "amqp://guest:guest@localhost:5672/"

# elasticsearch:
#   addr: "http://localhost:9200"
#   username: ""
#   password: ""
  
jwt:
  secret: "kumiko4869"
